name: "License checker"

on:
  push:
    branches:
      - master
      - 'release-*'
  pull_request:

jobs:
  check-license:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Check License Header
        uses: apache/skywalking-eyes@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          log: info
          token: ${{ github.token }}
          config: .licenserc.yaml

  dependency-license:
    name: Dependency licenses
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "11"
          cache: "maven"
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.16"
      - name: Check Dependencies Licenses
        run: |
          go install github.com/apache/skywalking-eyes/cmd/license-eye@442d462
          license-eye -c .licenserc.yaml dep check || exit 1

      - uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: License check(RAT)
        run: |
          mvn apache-rat:check -ntp
          find ./ -name rat.txt -print0 | xargs -0 -I file cat file > merged-rat.txt
          grep "Binaries" merged-rat.txt -C 3 && cat merged-rat.txt
