name: License checker

on:
  push:
    branches:
      - master
      - /^v[0-9]\..*$/
  pull_request:

jobs:
  check-license:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Check License Header
        uses: apache/skywalking-eyes@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          log: info
          config: .licenserc.yaml

  dependency-license:
    name: Dependency licenses
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "11"
          cache: "maven"
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.16"
      - name: Check Dependencies Licenses
        run: |
          go install github.com/apache/skywalking-eyes/cmd/license-eye@442d462
          license-eye dependency resolve --summary ./hugegraph-dist/release-docs/LICENSE.tpl || exit 1
          if [ ! -z "$(git diff -U0 ./hugegraph-dist/release-docs/LICENSE)" ]; then
            echo "LICENSE file is not updated correctly"
            git diff -U0 ./hugegraph-dist/release-docs/LICENSE
            exit 1
          fi
